"""empty message

Revision ID: ef61e41b5c3b
Revises: 
Create Date: 2024-08-20 21:34:57.431467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef61e41b5c3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__categories'))
    )
    op.create_index(op.f('ix__categories__id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix__categories__name'), 'categories', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users'))
    )
    op.create_index(op.f('ix__users__id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix__users__telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix__users__username'), 'users', ['username'], unique=True)
    op.create_table('salons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__salons__user_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__salons'))
    )
    op.create_index(op.f('ix__salons__id'), 'salons', ['id'], unique=False)
    op.create_index(op.f('ix__salons__name'), 'salons', ['name'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.Column('salon_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk__services__category_id__categories')),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], name=op.f('fk__services__salon_id__salons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__services'))
    )
    op.create_index(op.f('ix__services__id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix__services__name'), 'services', ['name'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], name=op.f('fk__subscriptions__salon_id__salons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__subscriptions'))
    )
    op.create_index(op.f('ix__subscriptions__id'), 'subscriptions', ['id'], unique=False)
    op.create_table('advertisements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('is_vip', sa.Boolean(), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk__advertisements__service_id__services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__advertisements'))
    )
    op.create_index(op.f('ix__advertisements__id'), 'advertisements', ['id'], unique=False)
    op.create_index(op.f('ix__advertisements__title'), 'advertisements', ['title'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('booking_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk__bookings__service_id__services')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__bookings__user_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__bookings'))
    )
    op.create_index(op.f('ix__bookings__id'), 'bookings', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk__payments__subscription_id__subscriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__payments'))
    )
    op.create_index(op.f('ix__payments__id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__payments__id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix__bookings__id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix__advertisements__title'), table_name='advertisements')
    op.drop_index(op.f('ix__advertisements__id'), table_name='advertisements')
    op.drop_table('advertisements')
    op.drop_index(op.f('ix__subscriptions__id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix__services__name'), table_name='services')
    op.drop_index(op.f('ix__services__id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix__salons__name'), table_name='salons')
    op.drop_index(op.f('ix__salons__id'), table_name='salons')
    op.drop_table('salons')
    op.drop_index(op.f('ix__users__username'), table_name='users')
    op.drop_index(op.f('ix__users__telegram_id'), table_name='users')
    op.drop_index(op.f('ix__users__id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix__categories__name'), table_name='categories')
    op.drop_index(op.f('ix__categories__id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
