"""empty message

Revision ID: a9d0404e410c
Revises: 862b5cb8c3da
Create Date: 2024-08-28 20:19:43.695609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d0404e410c'
down_revision: Union[str, None] = '862b5cb8c3da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix__users__telegram_id', table_name='users')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix__users__telegram_id', 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###
