"""empty message

Revision ID: 862b5cb8c3da
Revises: ef61e41b5c3b
Create Date: 2024-08-26 13:12:19.858558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '862b5cb8c3da'
down_revision: Union[str, None] = 'ef61e41b5c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('AT_HOME', 'IN_SALON', 'WITH_DEPARTURE', 'ALL', name='servicelocation').create(op.get_bind())
    op.add_column('services', sa.Column('service_location', postgresql.ENUM('AT_HOME', 'IN_SALON', 'WITH_DEPARTURE', 'ALL', name='servicelocation', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'service_location')
    sa.Enum('AT_HOME', 'IN_SALON', 'WITH_DEPARTURE', 'ALL', name='servicelocation').drop(op.get_bind())
    # ### end Alembic commands ###
